from __future__ import annotations

from typing import Final

# Stable FQL1 language and native request bounds shared by every SDK query path.
FLOW_QUERY_MAX_BYTES: Final = 16 * 1024
FLOW_QUERY_MAX_TOKENS: Final = 256
FLOW_QUERY_MAX_PARAMETERS: Final = 64
FLOW_QUERY_MAX_PARAMETER_NAME_BYTES: Final = 128
FLOW_QUERY_MAX_PREDICATES: Final = 12
FLOW_QUERY_MAX_IN_VALUES: Final = 20
FLOW_QUERY_MAX_ORDER_FIELDS: Final = 2
FLOW_QUERY_MAX_RETURN_FIELDS: Final = 32
FLOW_QUERY_MAX_RESULTS: Final = 100
FLOW_QUERY_MAX_PARTITION_BYTES: Final = 65_535
# No legal FQL1 bound binary can exceed the partition-key wire ceiling.
FLOW_QUERY_MAX_PARAMETER_VALUE_BYTES: Final = FLOW_QUERY_MAX_PARTITION_BYTES
# Partitioned state keys reserve 52 bytes for ``f:{sha256-tag}:s:``.
FLOW_QUERY_MAX_RUN_ID_BYTES: Final = FLOW_QUERY_MAX_PARTITION_BYTES - 52
FLOW_QUERY_MAX_FIELD_VALUE_BYTES: Final = 1_024
FLOW_QUERY_MAX_METADATA_NAME_BYTES: Final = 64
FLOW_QUERY_MAX_STATE_NAME_BYTES: Final = 64
FLOW_QUERY_MIN_CURSOR_BYTES: Final = 16
FLOW_QUERY_MAX_CURSOR_BYTES: Final = 4_096


__all__ = [
    "FLOW_QUERY_MAX_BYTES",
    "FLOW_QUERY_MAX_CURSOR_BYTES",
    "FLOW_QUERY_MAX_FIELD_VALUE_BYTES",
    "FLOW_QUERY_MAX_IN_VALUES",
    "FLOW_QUERY_MAX_METADATA_NAME_BYTES",
    "FLOW_QUERY_MAX_ORDER_FIELDS",
    "FLOW_QUERY_MAX_PARAMETERS",
    "FLOW_QUERY_MAX_PARAMETER_NAME_BYTES",
    "FLOW_QUERY_MAX_PARAMETER_VALUE_BYTES",
    "FLOW_QUERY_MAX_PARTITION_BYTES",
    "FLOW_QUERY_MAX_PREDICATES",
    "FLOW_QUERY_MAX_RESULTS",
    "FLOW_QUERY_MAX_RETURN_FIELDS",
    "FLOW_QUERY_MAX_RUN_ID_BYTES",
    "FLOW_QUERY_MAX_STATE_NAME_BYTES",
    "FLOW_QUERY_MAX_TOKENS",
    "FLOW_QUERY_MIN_CURSOR_BYTES",
]
