from __future__ import annotations

import struct
from dataclasses import dataclass
from typing import Any

from ferricstore.flow_options import FLOW_OPTION_FIELD_NAMES

_MAGIC = b"FSNP"


_REQUEST_VERSION = 0x01


_RESPONSE_VERSION = 0x81


_HEADER = struct.Struct(">4sBBIHQI")


_STATUS = struct.Struct(">H")


_FLAG_TRACE = 0x01


_FLAG_COMPRESSED = 0x08


_FLAG_CUSTOM_PAYLOAD = 0x02


_FLAG_MORE_CHUNKS = 0x20


_OP_PIPELINE = 0x000E


_OP_STARTUP = 0x000C


_OP_AUTH = 0x0002


_OP_SUBSCRIBE_EVENTS = 0x0011


_OP_UNSUBSCRIBE_EVENTS = 0x0012


_OP_COMMAND_EXEC = 0x0100


_OP_GET = 0x0101


_OP_SET = 0x0102


_OP_MGET = 0x0104


_OP_MSET = 0x0105


_OP_FLOW_GET = 0x0202


_OP_FLOW_CLAIM_DUE = 0x0203


_OP_FLOW_VALUE_MGET = 0x020C


_OP_FLOW_CREATE_MANY = 0x020F


_OP_FLOW_COMPLETE_MANY = 0x0210


_OP_FLOW_TRANSITION_MANY = 0x0211


_OP_FLOW_RETRY_MANY = 0x0212


_OP_FLOW_FAIL_MANY = 0x0213


_OP_FLOW_CANCEL_MANY = 0x0214


_OP_FLOW_RUN_STEPS_MANY = 0x0224


_STATUS_OK = 0


_STATUS_BUSY = 4


_COMPACT_FLOW_CLAIM_JOBS = 0x80


_COMPACT_OK_LIST = 0x81


_COMPACT_KV_GET = 0x82


_COMPACT_KV_MGET = 0x83


_COMPACT_FLOW_RECORD = 0x84


_COMPACT_FLOW_RECORD_LIST = 0x85


_COMPACT_BINARY_LIST_LIST = 0x86


_COMPACT_BINARY_MAP_LIST = 0x87


_COMPACT_INTEGER_LIST = 0x88


_COMPACT_KV_MGET_FIXED = 0x89


_COMPACT_FLOW_CREATE_MANY_REQUEST = 0x90


_COMPACT_FLOW_CREATE_MANY_PARTITION_REQUEST = 0x96


_COMPACT_FLOW_CREATE_MANY_MIXED_REQUEST = 0x9E


_COMPACT_FLOW_CLAIM_DUE_REQUEST = 0x91


_COMPACT_FLOW_COMPLETE_MANY_REQUEST = 0x92


_COMPACT_FLOW_COMPLETE_MANY_OK_REQUEST = 0x93


_COMPACT_PIPELINE_REQUEST = 0x94


_COMPACT_PIPELINE_RESPONSE = 0x95


_COMPACT_FLOW_RETRY_MANY_REQUEST = 0x97


_COMPACT_FLOW_RETRY_MANY_OK_REQUEST = 0x98


_COMPACT_FLOW_CANCEL_MANY_REQUEST = 0x99


_COMPACT_FLOW_CANCEL_MANY_OK_REQUEST = 0x9A


_COMPACT_FLOW_TRANSITION_MANY_REQUEST = 0x9B


_COMPACT_FLOW_TRANSITION_MANY_OK_REQUEST = 0x9C


_COMPACT_FLOW_VALUE_MGET_REQUEST = 0x9D


_COMPACT_FLOW_LIST_REQUEST = 0x9F


_COMPACT_PIPELINE_HEADER = struct.Struct(">BBI")


_COMPACT_U32 = struct.Struct(">I")


_COMPACT_I64 = struct.Struct(">q")


_COMPACT_F64 = struct.Struct(">d")


_NULL_U32 = 0xFFFFFFFF


_I64_MIN = -(1 << 63)


_DEFAULT_PROTOCOL_LANES = 8


_DEFAULT_MAX_RESPONSE_BYTES = 64 * 1024 * 1024


_DEFAULT_MAX_DECOMPRESSED_RESPONSE_BYTES = 128 * 1024 * 1024


_DEFAULT_MAX_RESPONSE_CHUNKS = 1024


_ASYNC_ADAPTER_FANOUT_LIMIT = 16


_DEFAULT_MAX_EVENT_QUEUE_SIZE = 10_000


_DEFAULT_MAX_DECODED_COLLECTION_ITEMS = 100_000


_MAX_LANE_ID = 0xFFFFFFFF


_USE_ADAPTER_TIMEOUT = object()


_ROUTE_SLOT_COUNT = 1024


_ROUTE_SLOT_MASK = _ROUTE_SLOT_COUNT - 1


_COMPACT_HGET_PIPELINE_MODE = 18


_COMPACT_SISMEMBER_PIPELINE_MODE = 19


_COMPACT_LRANGE_PIPELINE_MODE = 20


_COMPACT_ZRANGE_PIPELINE_MODE = 21


_COMPACT_HSET_PIPELINE_MODE = 22


_COMPACT_LPUSH_PIPELINE_MODE = 23


_COMPACT_RPUSH_PIPELINE_MODE = 24


_COMPACT_SADD_PIPELINE_MODE = 25


_COMPACT_ZADD_PIPELINE_MODE = 26


_COMPACT_SMEMBERS_PIPELINE_MODE = 27


_COMPACT_HMGET_PIPELINE_MODE = 28


_COMPACT_ZSCORE_PIPELINE_MODE = 29


_COMPACT_HGETALL_PIPELINE_MODE = 30


_COMPACT_SREM_PIPELINE_MODE = 31


_COMPACT_ZREM_PIPELINE_MODE = 32


_FLOW_RECORD_LIST_OPCODES = {
    0x020E,  # FLOW.LIST
    0x0217,  # FLOW.TERMINALS
    0x0218,  # FLOW.FAILURES
    0x0219,  # FLOW.BY_PARENT
    0x021A,  # FLOW.BY_ROOT
    0x021B,  # FLOW.BY_CORRELATION
    0x021D,  # FLOW.STUCK
}


_FLOW_RECORD_FIELD_KEYS = (
    b"",
    b"id",
    b"type",
    b"state",
    b"version",
    b"priority",
    b"partition_key",
    b"payload_ref",
    b"result_ref",
    b"error_ref",
    b"payload",
    b"result",
    b"error",
    b"created_at_ms",
    b"updated_at_ms",
    b"next_run_at_ms",
    b"lease_deadline_ms",
    b"lease_owner",
    b"lease_token",
    b"fencing_token",
    b"attempts",
    b"history_max_events",
    b"history_hot_max_events",
    b"child_groups",
    b"parent_flow_id",
    b"parent_partition_key",
    b"root_flow_id",
    b"correlation_id",
    b"terminal_retention_until_ms",
    b"ttl_ms",
    b"retention_ttl_ms",
    b"run_state",
    b"value_refs",
    b"values",
    b"payload_omitted",
    b"payload_size",
    b"result_omitted",
    b"result_size",
    b"error_omitted",
    b"error_size",
    b"max_attempts",
    b"attributes",
)


_FLOW_RECORD_FIELD_KEYS_LEN = len(_FLOW_RECORD_FIELD_KEYS)


_PLAIN_SCHEMES = {"ferric"}


_TLS_SCHEMES = {"ferrics"}


_SUPPORTED_SCHEMES = _PLAIN_SCHEMES | _TLS_SCHEMES


_OPCODES = {
    "HELLO": 0x0001,
    "AUTH": 0x0002,
    "PING": 0x0003,
    "CLIENT.SETNAME": 0x0004,
    "CLIENT.INFO": 0x0005,
    "ROUTE": 0x0006,
    "SHARDS": 0x0007,
    "BACKPRESSURE": 0x0008,
    "QUIT": 0x0009,
    "GOAWAY": 0x000A,
    "OPTIONS": 0x000B,
    "STARTUP": 0x000C,
    "WINDOW_UPDATE": 0x000D,
    "PIPELINE": _OP_PIPELINE,
    "ROUTE_BATCH": 0x000F,
    "EVENT": 0x0010,
    "SUBSCRIBE_EVENTS": _OP_SUBSCRIBE_EVENTS,
    "UNSUBSCRIBE_EVENTS": _OP_UNSUBSCRIBE_EVENTS,
    "COMMAND_EXEC": _OP_COMMAND_EXEC,
    "GET": _OP_GET,
    "SET": _OP_SET,
    "DEL": 0x0103,
    "MGET": _OP_MGET,
    "MSET": _OP_MSET,
    "CAS": 0x0106,
    "LOCK": 0x0107,
    "UNLOCK": 0x0108,
    "EXTEND": 0x0109,
    "RATELIMIT.ADD": 0x010A,
    "FETCH_OR_COMPUTE": 0x010B,
    "FETCH_OR_COMPUTE_RESULT": 0x010C,
    "FETCH_OR_COMPUTE_ERROR": 0x010D,
    "HSET": 0x0110,
    "HGET": 0x0111,
    "HMGET": 0x0112,
    "HGETALL": 0x0113,
    "LPUSH": 0x0120,
    "RPUSH": 0x0121,
    "LPOP": 0x0122,
    "RPOP": 0x0123,
    "LRANGE": 0x0124,
    "SADD": 0x0130,
    "SREM": 0x0131,
    "SMEMBERS": 0x0132,
    "SISMEMBER": 0x0133,
    "ZADD": 0x0140,
    "ZREM": 0x0141,
    "ZRANGE": 0x0142,
    "ZSCORE": 0x0143,
    "CLUSTER.HEALTH": 0x0301,
    "CLUSTER.STATS": 0x0302,
    "CLUSTER.KEYSLOT": 0x0303,
    "CLUSTER.SLOTS": 0x0304,
    "CLUSTER.STATUS": 0x0305,
    "CLUSTER.JOIN": 0x0306,
    "CLUSTER.LEAVE": 0x0307,
    "CLUSTER.FAILOVER": 0x0308,
    "CLUSTER.PROMOTE": 0x0309,
    "CLUSTER.DEMOTE": 0x030A,
    "CLUSTER.ROLE": 0x030B,
    "FERRICSTORE.KEY_INFO": 0x030C,
    "FERRICSTORE.CONFIG": 0x030D,
    "FERRICSTORE.HOTNESS": 0x030E,
    "FERRICSTORE.METRICS": 0x030F,
    "FERRICSTORE.BLOBGC": 0x0310,
    "FLOW.CREATE": 0x0201,
    "FLOW.GET": 0x0202,
    "FLOW.CLAIM_DUE": 0x0203,
    "FLOW.COMPLETE": 0x0204,
    "FLOW.TRANSITION": 0x0205,
    "FLOW.RETRY": 0x0206,
    "FLOW.FAIL": 0x0207,
    "FLOW.CANCEL": 0x0208,
    "FLOW.EXTEND_LEASE": 0x0209,
    "FLOW.HISTORY": 0x020A,
    "FLOW.VALUE.PUT": 0x020B,
    "FLOW.VALUE.MGET": 0x020C,
    "FLOW.SIGNAL": 0x020D,
    "FLOW.LIST": 0x020E,
    "FLOW.CREATE_MANY": 0x020F,
    "FLOW.COMPLETE_MANY": 0x0210,
    "FLOW.TRANSITION_MANY": 0x0211,
    "FLOW.RETRY_MANY": 0x0212,
    "FLOW.FAIL_MANY": 0x0213,
    "FLOW.CANCEL_MANY": 0x0214,
    "FLOW.RECLAIM": 0x0215,
    "FLOW.REWIND": 0x0216,
    "FLOW.TERMINALS": 0x0217,
    "FLOW.FAILURES": 0x0218,
    "FLOW.BY_PARENT": 0x0219,
    "FLOW.BY_ROOT": 0x021A,
    "FLOW.BY_CORRELATION": 0x021B,
    "FLOW.INFO": 0x021C,
    "FLOW.STUCK": 0x021D,
    "FLOW.POLICY.SET": 0x021E,
    "FLOW.POLICY.GET": 0x021F,
    "FLOW.SPAWN_CHILDREN": 0x0220,
    "FLOW.RETENTION_CLEANUP": 0x0221,
    "FLOW.STEP_CONTINUE": 0x0222,
    "FLOW.START_AND_CLAIM": 0x0223,
    "FLOW.RUN_STEPS_MANY": _OP_FLOW_RUN_STEPS_MANY,
    "FLOW.SCHEDULE.CREATE": 0x0225,
    "FLOW.SCHEDULE.GET": 0x0226,
    "FLOW.SCHEDULE.DELETE": 0x0227,
    "FLOW.SCHEDULE.FIRE_DUE": 0x0228,
    "FLOW.SCHEDULE.LIST": 0x0229,
    "FLOW.SCHEDULE.FIRE": 0x022A,
    "FLOW.SCHEDULE.PAUSE": 0x022B,
    "FLOW.SCHEDULE.RESUME": 0x022C,
    "FLOW.STATS": 0x022D,
    "FLOW.ATTRIBUTES": 0x022E,
    "FLOW.ATTRIBUTE_VALUES": 0x022F,
    "FLOW.SEARCH": 0x0230,
    "FLOW.EFFECT.RESERVE": 0x0240,
    "FLOW.EFFECT.CONFIRM": 0x0241,
    "FLOW.EFFECT.FAIL": 0x0242,
    "FLOW.EFFECT.COMPENSATE": 0x0243,
    "FLOW.EFFECT.GET": 0x0244,
    "FLOW.GOVERNANCE.LEDGER": 0x0245,
    "FLOW.APPROVAL.REQUEST": 0x0246,
    "FLOW.APPROVAL.APPROVE": 0x0247,
    "FLOW.APPROVAL.REJECT": 0x0248,
    "FLOW.APPROVAL.GET": 0x0249,
    "FLOW.CIRCUIT.OPEN": 0x024A,
    "FLOW.CIRCUIT.CLOSE": 0x024B,
    "FLOW.CIRCUIT.GET": 0x024C,
    "FLOW.BUDGET.RESERVE": 0x024D,
    "FLOW.BUDGET.GET": 0x024E,
    "FLOW.LIMIT.LEASE": 0x024F,
    "FLOW.LIMIT.SPEND": 0x0250,
    "FLOW.LIMIT.RELEASE": 0x0251,
    "FLOW.LIMIT.GET": 0x0252,
    "FLOW.APPROVAL.LIST": 0x0253,
    "FLOW.GOVERNANCE.OVERVIEW": 0x0254,
    "FLOW.BUDGET.LIST": 0x0255,
    "FLOW.LIMIT.LIST": 0x0256,
    "FLOW.BUDGET.COMMIT": 0x0257,
    "FLOW.BUDGET.RELEASE": 0x0258,
}


_CONTROL_OPCODES = set(range(0x0001, 0x0013))


_SAFE_CONTROL_RETRY_COMMANDS = frozenset({"OPTIONS", "PING", "SHARDS"})


_STATEFUL_COMMAND_EXEC = {
    "BLMOVE",
    "BLMPOP",
    "BLPOP",
    "BRPOP",
    "DISCARD",
    "EXEC",
    "MULTI",
    "PSUBSCRIBE",
    "PUNSUBSCRIBE",
    "SUBSCRIBE",
    "UNSUBSCRIBE",
    "UNWATCH",
    "WATCH",
    "XREAD",
    "XREADGROUP",
}


_FIELD_NAMES = FLOW_OPTION_FIELD_NAMES


_BOOL_FIELDS = {
    "consistent_projection",
    "full",
    "idempotent",
    "include_cold",
    "independent",
    "local_cache",
    "override",
    "overwrite",
    "reclaim_expired",
    "rev",
    "terminal_only",
    "terminal_local_only",
    "values",
}


_COMPACT_COLLECTION_MARKERS = frozenset(
    {
        _COMPACT_FLOW_CLAIM_JOBS,
        _COMPACT_OK_LIST,
        _COMPACT_KV_MGET,
        _COMPACT_FLOW_RECORD_LIST,
        _COMPACT_BINARY_LIST_LIST,
        _COMPACT_BINARY_MAP_LIST,
        _COMPACT_INTEGER_LIST,
        _COMPACT_KV_MGET_FIXED,
        _COMPACT_PIPELINE_RESPONSE,
    }
)


_COMPACT_COLLECTION_MIN_ITEM_BYTES = {
    _COMPACT_FLOW_CLAIM_JOBS: 20,
    _COMPACT_KV_MGET: 1,
    _COMPACT_FLOW_RECORD_LIST: 5,
    _COMPACT_BINARY_LIST_LIST: 4,
    _COMPACT_BINARY_MAP_LIST: 4,
    _COMPACT_INTEGER_LIST: 8,
    _COMPACT_PIPELINE_RESPONSE: 1,
}


_FLOW_POLICY_FIELD_NAMES = {
    "INDEXED_ATTRIBUTES": "indexed_attributes",
    "MODE": "mode",
}


@dataclass(frozen=True, slots=True)
class ProtocolCommand:
    opcode: int
    payload: dict[str, Any] | bytes
    lane_id: int = 1
    flags: int = 0


@dataclass(frozen=True, slots=True)
class ProtocolResponse:
    lane_id: int
    opcode: int
    request_id: int
    flags: int
    status: int
    value: Any
    trace: dict[str, Any] | None = None


__all__ = [
    "_ASYNC_ADAPTER_FANOUT_LIMIT",
    "_BOOL_FIELDS",
    "_COMPACT_BINARY_LIST_LIST",
    "_COMPACT_BINARY_MAP_LIST",
    "_COMPACT_COLLECTION_MARKERS",
    "_COMPACT_COLLECTION_MIN_ITEM_BYTES",
    "_COMPACT_F64",
    "_COMPACT_FLOW_CANCEL_MANY_OK_REQUEST",
    "_COMPACT_FLOW_CANCEL_MANY_REQUEST",
    "_COMPACT_FLOW_CLAIM_DUE_REQUEST",
    "_COMPACT_FLOW_CLAIM_JOBS",
    "_COMPACT_FLOW_COMPLETE_MANY_OK_REQUEST",
    "_COMPACT_FLOW_COMPLETE_MANY_REQUEST",
    "_COMPACT_FLOW_CREATE_MANY_MIXED_REQUEST",
    "_COMPACT_FLOW_CREATE_MANY_PARTITION_REQUEST",
    "_COMPACT_FLOW_CREATE_MANY_REQUEST",
    "_COMPACT_FLOW_LIST_REQUEST",
    "_COMPACT_FLOW_RECORD",
    "_COMPACT_FLOW_RECORD_LIST",
    "_COMPACT_FLOW_RETRY_MANY_OK_REQUEST",
    "_COMPACT_FLOW_RETRY_MANY_REQUEST",
    "_COMPACT_FLOW_TRANSITION_MANY_OK_REQUEST",
    "_COMPACT_FLOW_TRANSITION_MANY_REQUEST",
    "_COMPACT_FLOW_VALUE_MGET_REQUEST",
    "_COMPACT_HGETALL_PIPELINE_MODE",
    "_COMPACT_HGET_PIPELINE_MODE",
    "_COMPACT_HMGET_PIPELINE_MODE",
    "_COMPACT_HSET_PIPELINE_MODE",
    "_COMPACT_I64",
    "_COMPACT_INTEGER_LIST",
    "_COMPACT_KV_GET",
    "_COMPACT_KV_MGET",
    "_COMPACT_KV_MGET_FIXED",
    "_COMPACT_LPUSH_PIPELINE_MODE",
    "_COMPACT_LRANGE_PIPELINE_MODE",
    "_COMPACT_OK_LIST",
    "_COMPACT_PIPELINE_HEADER",
    "_COMPACT_PIPELINE_REQUEST",
    "_COMPACT_PIPELINE_RESPONSE",
    "_COMPACT_RPUSH_PIPELINE_MODE",
    "_COMPACT_SADD_PIPELINE_MODE",
    "_COMPACT_SISMEMBER_PIPELINE_MODE",
    "_COMPACT_SMEMBERS_PIPELINE_MODE",
    "_COMPACT_SREM_PIPELINE_MODE",
    "_COMPACT_U32",
    "_COMPACT_ZADD_PIPELINE_MODE",
    "_COMPACT_ZRANGE_PIPELINE_MODE",
    "_COMPACT_ZREM_PIPELINE_MODE",
    "_COMPACT_ZSCORE_PIPELINE_MODE",
    "_CONTROL_OPCODES",
    "_DEFAULT_MAX_DECODED_COLLECTION_ITEMS",
    "_DEFAULT_MAX_DECOMPRESSED_RESPONSE_BYTES",
    "_DEFAULT_MAX_EVENT_QUEUE_SIZE",
    "_DEFAULT_MAX_RESPONSE_BYTES",
    "_DEFAULT_MAX_RESPONSE_CHUNKS",
    "_DEFAULT_PROTOCOL_LANES",
    "_FIELD_NAMES",
    "_FLAG_COMPRESSED",
    "_FLAG_CUSTOM_PAYLOAD",
    "_FLAG_MORE_CHUNKS",
    "_FLAG_TRACE",
    "_FLOW_POLICY_FIELD_NAMES",
    "_FLOW_RECORD_FIELD_KEYS",
    "_FLOW_RECORD_FIELD_KEYS_LEN",
    "_FLOW_RECORD_LIST_OPCODES",
    "_HEADER",
    "_I64_MIN",
    "_MAGIC",
    "_MAX_LANE_ID",
    "_NULL_U32",
    "_OPCODES",
    "_OP_AUTH",
    "_OP_COMMAND_EXEC",
    "_OP_FLOW_CANCEL_MANY",
    "_OP_FLOW_CLAIM_DUE",
    "_OP_FLOW_COMPLETE_MANY",
    "_OP_FLOW_CREATE_MANY",
    "_OP_FLOW_FAIL_MANY",
    "_OP_FLOW_GET",
    "_OP_FLOW_RETRY_MANY",
    "_OP_FLOW_RUN_STEPS_MANY",
    "_OP_FLOW_TRANSITION_MANY",
    "_OP_FLOW_VALUE_MGET",
    "_OP_GET",
    "_OP_MGET",
    "_OP_MSET",
    "_OP_PIPELINE",
    "_OP_SET",
    "_OP_STARTUP",
    "_OP_SUBSCRIBE_EVENTS",
    "_OP_UNSUBSCRIBE_EVENTS",
    "_PLAIN_SCHEMES",
    "_REQUEST_VERSION",
    "_RESPONSE_VERSION",
    "_ROUTE_SLOT_COUNT",
    "_ROUTE_SLOT_MASK",
    "_SAFE_CONTROL_RETRY_COMMANDS",
    "_STATEFUL_COMMAND_EXEC",
    "_STATUS",
    "_STATUS_BUSY",
    "_STATUS_OK",
    "_SUPPORTED_SCHEMES",
    "_TLS_SCHEMES",
    "_USE_ADAPTER_TIMEOUT",
    "ProtocolCommand",
    "ProtocolResponse",
]
