from __future__ import annotations

import argparse
import ast
import subprocess
import sys
from pathlib import Path

REPOSITORY = Path(__file__).resolve().parents[1]
SOURCE = REPOSITORY / "src" / "ferricstore" / "commands.py"
TARGET = REPOSITORY / "src" / "ferricstore" / "async_commands.py"


def _sync_class_source() -> str:
    source = SOURCE.read_text()
    tree = ast.parse(source)
    node = next(
        item
        for item in tree.body
        if isinstance(item, ast.ClassDef) and item.name == "DataCommandsMixin"
    )
    if node.end_lineno is None:
        raise RuntimeError("DataCommandsMixin has no source extent")
    return "\n".join(source.splitlines()[node.lineno - 1 : node.end_lineno])


class _CommandCallCollector(ast.NodeVisitor):
    """Find executable self.command calls without descending into nested scopes."""

    def __init__(self) -> None:
        self.calls: list[ast.Call] = []

    def visit_FunctionDef(self, node: ast.FunctionDef) -> None:
        return None

    def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> None:
        return None

    def visit_Lambda(self, node: ast.Lambda) -> None:
        return None

    def visit_Call(self, node: ast.Call) -> None:
        function = node.func
        if (
            isinstance(function, ast.Attribute)
            and function.attr == "command"
            and isinstance(function.value, ast.Name)
            and function.value.id == "self"
        ):
            self.calls.append(node)
        self.generic_visit(node)


def _source_offset(
    lines: list[str],
    line_offsets: list[int],
    lineno: int,
    utf8_col_offset: int,
) -> int:
    line = lines[lineno - 1]
    character_offset = len(line.encode()[:utf8_col_offset].decode())
    return line_offsets[lineno - 1] + character_offset


def _async_class_source(source: str) -> str:
    tree = ast.parse(source)
    classes = [node for node in tree.body if isinstance(node, ast.ClassDef)]
    if len(classes) != 1 or classes[0].name != "DataCommandsMixin":
        raise RuntimeError("expected exactly one DataCommandsMixin class")
    class_node = classes[0]

    lines = source.splitlines(keepends=True)
    line_offsets: list[int] = []
    offset = 0
    for line in lines:
        line_offsets.append(offset)
        offset += len(line)

    replacements: list[tuple[int, int, str]] = []
    class_start = _source_offset(lines, line_offsets, class_node.lineno, class_node.col_offset)
    name_start = source.find(
        class_node.name,
        class_start,
        class_start + len(lines[class_node.lineno - 1]),
    )
    if name_start < 0:
        raise RuntimeError("could not locate DataCommandsMixin name")
    replacements.append((name_start, name_start + len(class_node.name), "AsyncDataCommandsMixin"))

    for method in class_node.body:
        if not isinstance(method, ast.FunctionDef):
            continue
        method_start = _source_offset(lines, line_offsets, method.lineno, method.col_offset)
        replacements.append((method_start, method_start, "async "))
        collector = _CommandCallCollector()
        for statement in method.body:
            collector.visit(statement)
        for call in collector.calls:
            call_start = _source_offset(lines, line_offsets, call.lineno, call.col_offset)
            replacements.append((call_start, call_start, "await "))

    docstring = ast.get_docstring(class_node, clean=False)
    if docstring is not None and class_node.body:
        expression = class_node.body[0]
        if isinstance(expression, ast.Expr) and isinstance(expression.value, ast.Constant):
            old_text = "Convenience methods for FerricStore data-structure commands."
            new_text = "Async convenience methods for FerricStore data-structure commands."
            value = expression.value
            value_start = _source_offset(lines, line_offsets, value.lineno, value.col_offset)
            value_end = _source_offset(
                lines,
                line_offsets,
                value.end_lineno or value.lineno,
                value.end_col_offset or value.col_offset,
            )
            text_start = source.find(old_text, value_start, value_end)
            if text_start >= 0:
                replacements.append((text_start, text_start + len(old_text), new_text))

    generated = source
    for start, end, replacement in sorted(replacements, reverse=True):
        generated = generated[:start] + replacement + generated[end:]
    compile(generated, "<generated async commands>", "exec")
    return generated


def render() -> str:
    class_source = _async_class_source(_sync_class_source())
    generated = f"""# Generated by tools/generate_async_commands.py; do not edit directly.
from __future__ import annotations

import builtins
from typing import Any

from ferricstore.codecs import Codec
from ferricstore.command_helpers import (
    _expire_args,
    _getex_args,
    _set_args,
    _validate_mset_slots,
    _xread_args,
)
from ferricstore.config_validation import validate_bool, validate_positive_int

{class_source}


__all__ = ["AsyncDataCommandsMixin"]
"""
    formatted = subprocess.run(
        [
            sys.executable,
            "-m",
            "ruff",
            "format",
            "--stdin-filename",
            str(TARGET),
            "-",
        ],
        input=generated,
        capture_output=True,
        check=True,
        text=True,
    )
    return formatted.stdout


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not TARGET.is_file() or TARGET.read_text() != expected:
            parser.error("generated async commands are stale; run tools/generate_async_commands.py")
        return 0
    TARGET.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
